export default asm`
(func $env.malloc (;0;) (import "env" "malloc") (param i32) (result i32))
(func $env.free (;1;) (import "env" "free") (param i32))
(func $env.calloc (;2;) (import "env" "calloc") (param i32 i32) (result i32))
(func $env.realloc (;3;) (import "env" "realloc") (param i32 i32) (result i32))
(func $env.aligned_alloc (;4;) (import "env" "aligned_alloc") (param i32 i32) (result i32))

(func $malloc (export "malloc") (param $size i32) (result i32)
  (call $env.malloc (local.get $size))
)
(func $free (export "free") (param $pointer i32)
  (call $env.free (local.get $pointer))
)
(func $calloc (export "calloc") (param $num i32) (param $size i32) (result i32)
  (call $env.calloc (local.get $num) (local.get $size))
)
(func $realloc (export "realloc") (param $pointer i32) (param $size i32) (result i32)
  (call $env.realloc (local.get $pointer) (local.get $size))
)
(func $aligned_alloc (export "alignedAlloc") (param $alignment i32) (param $size i32) (result i32)
  (call $env.realloc (local.get $alignment) (local.get $size))
)
`
