

export const accessof = 'accessof'
export const addressof = 'addressof'
export const offsetof = 'offsetof'
export const memcpy = 'memcpy'
export const sizeof = 'sizeof'
export const move = 'move'
export const staticCast = 'static_cast'
export const assert = 'assert'
export const indexOf = 'indexOf'
export const reinterpretCast = 'reinterpret_cast'
export const sharedPtr = 'SharedPtr'

export const structAccess = 'structAccess'
export const writePointer = 'writePointer'
export const ctypeEnumWrite = 'CTypeEnumWrite'
export const ctypeEnumRead = 'CTypeEnumRead'
export const definedMetaProperty = 'definedMetaProperty'

export const symbolStructAddress = 'symbolStructAddress'
export const symbolStruct = 'symbolStruct'
export const symbolStructMaxBaseTypeByteLength = 'symbolStructMaxBaseTypeByteLength'
export const symbolStructLength = 'symbolStructLength'
export const symbolStructKeysMeta = 'symbolStructKeysMeta'

export const atomicsPath = 'cheap/thread/atomics'
export const sizeofPath = 'cheap/std/sizeof'
export const definedMetaPropertyPath = 'cheap/function/definedMetaProperty'
export const memoryPath = 'cheap/std/memory'
export const symbolPath = 'cheap/symbol'
export const structAccessPath = 'cheap/std/structAccess'
export const ctypeEnumReadPath = 'cheap/ctypeEnumRead'
export const ctypeEnumWritePath = 'cheap/ctypeEnumWrite'
export const createThreadFromClass = 'createThreadFromClass'
export const createThreadFromFunction = 'createThreadFromFunction'
export const createThreadFromModule = 'createThreadFromModule'
export const cheapThreadPath = 'cheap/thread/thread'

export const typeArray = 'array'
export const typeBit = 'bit'
export const typePointer = 'pointer'
export const typeAnyptr = 'anyptr'
export const typeNullptr = 'nullptr'
export const typeMultiPointer = 'multiPointer'
export const typeUnion = 'union'
export const typeStruct = 'struct'
export const defined = 'defined'
export const args = 'args'
export const enableArgs = 'enableArgs'

export const tagAsm = 'asm'

export const prototype = 'prototype'

export const cstruct = 'struct'
export const cunion = 'union'
export const ctype = 'type'
export const cpointer = 'pointer'
export const carray = 'array'
export const cbitField = 'bit'
export const cignore = 'ignore'
export const cinline = 'inline'
export const cdeasync = 'deasync'

export const make = 'make'
export const unmake = 'unmake'
export const malloc = 'malloc'
export const calloc = 'calloc'
export const realloc = 'realloc'
export const alignedAlloc = 'aligned_alloc'
export const free = 'free'
export const Allocator = 'Allocator'
export const makeSharedPtr = 'makeSharedPtr'
export const AllocatorPath = 'cheap/heap'
export const makePath = 'cheap/std/make'
export const unmakePath = 'cheap/std/unmake'
export const makeSharedPtrPath = 'cheap/std/smartPtr/SharedPtr'

export const typeProperty = 'zzztype__'
export const levelProperty = 'zzzlevel__'
export const structProperty = 'zzzstruct__'

export const LINE = '___LINE__'
export const LINE_2 = '__LINE__'
export const FILE = '___FILE__'
export const FILE_2 = '__FILE__'
export const MODULE = '___MODULE__'
export const MODULE_2 = '__MODULE__'
